### PR TITLE
[POPLAR] Integrate the Camera Augmented Sensing Helper and its ToF calibration

### PR DESCRIPTION
**Pull request by kholk**
Add libcashctl, cashsvr, libpolyreg to the build, declare
TARGET_USES_CASH_EXTENSION to build the code in the camera HAL
and copy the tof_focus_calibration XML.

### CODE REVIEW

**Comment by alviteri** [comment]
can be merged at this point ? @jerpelea

**Comment by jerpelea** [comment]
not yet

**Comment by russel5** [comment]
Hi, can i used this for lilac?

**Comment by kholk** [comment]
Yoshino has some... quirk.
Check if the Poplar XML gives good focus, otherwise, please try Maple XML.
If none of them are giving good focus, I will calibrate Lilac and make a special one.


Thanks!

**Comment by russel5** [comment]
@kholk 
tried both options, the focus is still sometimes wrong.
especially when you switch from a close object to a distant focus, vice versa even more. A couple of times you move the camera and the focus starts working as it should.

**Comment by alviteri** [comment]
@jerpelea tested on poplar ... ok on some usecases

**Comment by Myself5** [comment]
@jerpelea Along with the latest cash fixes from today this is ready to rock.

**Comment by russel5** [comment]
Sorry for open it again, but why we don't had this in lilac?
@kholk @jerpelea

**Comment by kholk** [comment]
Lilac is not calibrated yet.
Please wait until I get some time to calibrate it. 

Thanks!

**Comment by russel5** [comment]
Any ETA?
@kholk

**Comment by kholk** [comment]
I'm planning enhancements for CASH (ToF range extension), to be done after the k4.9 bringup.
Lilac will get calibrated after implementing the enhancements, since all of them should get recalibrated to fully use the new stuff.

Please, be patient.

**Comment by russel5** [comment]
@kholk 3 month gone away. You have k4.9, you have android 9, but still don't have right focus on lilac. All other devices have this features, but not lilac. Why?
If you do not want make it for lilac just tell, I'm open issue on bug tracket, because focuse not work on lilac at all, always try focus to macro and after few attempts focus as it should

**Comment by kholk** [comment]
@russel5 The k4.9 is not ready yet and I've also been (still am, actually) on vacation as well.

Things will come. Please be patient. Thanks.

**Pull request merged**
