### PR TITLE
poplar: use ECNS module in ADSP for BLUETOOTH_SCO_HEADSET

### PR DESCRIPTION
**Pull request by alviteri**
this fix the audio on some BT speakers (tested with mine)
AUDIO_DEVICE_OUT_ALL_SCO enabled incompatible bt_sco usecase for yoshino
AUDIO_DEVICE_OUT_BLUETOOTH_SCO_HEADSET enables ECNS module in ADSP

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by alviteri** [comment]
tested for now poplar .... tested needed on maple @kholk

**Comment by jerpelea** [comment]
aosp hal?

**Comment by alviteri** [comment]
yeah this morning I can't play music from spotify to my BT speaker .... saw logs and AUDIO_DEVICE_OUT_ALL_SCO causes some pcm_prepare fails

**Comment by jerpelea** [comment]
thos shouls be common on all yoshino devices

**Comment by alviteri** [comment]
I can confirm lilac and Poplar were affected but maple has not Oreo release so .... I need to be sure ... I will check later

**Comment by jerpelea** [comment]
it is the same for maple push it

**Pull request merged**
