### PR TITLE
poplar: use speaker for voice call speaker usecase

### PR DESCRIPTION
**Pull request by alviteri**
route out voice call to speaker (bottom, right)

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by alviteri** [comment]
ping @kholk

**Comment by alviteri** [comment]
ping @abioteau

**Comment by alviteri** [comment]
@jerpelea this is ok .... on speaker mode (right/bottom) speaker should be used

**Comment by kholk** [comment]
Are you sure? The microphone that we use is the one on the bottom, so we should prefer the other speaker!

**Comment by alviteri** [comment]
On stock I can see how it uses right speaker for that usecase .... Mmmm also tone also Loire ... Why here it should be different ?

**Comment by kholk** [comment]
Because stock has AANC. We should enable that before redirecting the speaker output, otherwise it's a mess!

**Comment by alviteri** [comment]
Just do a call with any Loire aosp ... Then enable speaker I can't follow you

**Comment by kholk** [comment]
With that modification without AANC it's more likely to get echo on the microphone!

**Pull request closed without merging**
